security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: jmd
    password: jmd123456
  oauth2:
    client:
      clientId: webApp2
      clientSecret: webApp2
      accessTokenUri: http://192.168.21.24:9093/auth/oauth/token
      userAuthorizationUri: http://192.168.21.24:9093/auth/oauth/authorize
    resource:
      id: jmd-monitor
      user-info-uri: http://192.168.21.24:9093/auth/user
      prefer-token-info: false
      filter-order: 3
spring:
  boot:
    admin:
      client:
        metadata:
          user.name: ${security.user.name}
          user.password: ${security.user.password}
        prefer-ip: true
        management-base-url: ${management.context-path}
        service-base-url: ${management.context-path}
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
      turbine:
        clusters: main,auth
        location: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jmd?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/spring/cloud/jmd/db/mysql/*/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: spring.cloud.jmd.db.mysql.*.entity
  typeEnumsPackage: spring.cloud.jmd.db.mysql.*.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
info:
  app:
    name: monitor
    description: 监控服务
  build:
    groupId: spring.cloud.jmd
    artifact: monitor
    version: 0.0.1-SNAPSHOT
logging:
  level:
    root: info
  path: log/${spring.application.name}
turbine:
  instanceUrlSuffix:
    auth: auth/mgmt/hystrix.stream
    main:  mgmt/hystrix.stream
  aggregator:
    clusterConfig: main,auth
  cluster-name-expression: metadata['cluster']
  appConfig: JMD-TEST-HI,JMD-CONFIG,JMD-AUTH,JMD-ZUUl