zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://127.0.0.1:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1
spring:
  sleuth:
    enabled: false
  sampler:
    percentage: 1.0
  rabbitmq:
    host: localhost
    rabbitmq:
      port: 15672
      username: guest
      password: guest
logging:
  level:
    root: WARN