zuul:
  add-host-header: true
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    auth:
      path: /auth/**
      strip-prefix: false
      sensitiveHeaders:
      serviceId: jmd-auth1
    app:
      path: /app/**
      strip-prefix: false
      sensitiveHeaders: "*"
      serviceId: jmd-app
    webApp:
      path: /web/**
      strip-prefix: true
      sensitiveHeaders: "*"
      serviceId: jmd-app
    monitor:
      path: /monitor/**
      strip-prefix: false
      sensitiveHeaders:
      serviceId: jmd-monitor
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  session:
    store-type: none