security:
  basic:
    enabled: true
    path: /mgmt
  user:
    name: jmd
    password: jmd123456
  oauth2:
    resource:
      filter-order: 3
management:
  security:
    enabled: true
  context-path: /mgmt
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###
spring:
  rabbitmq:
    host: localhost
    rabbitmq:
      port: 15672
      username: guest
      password: guest
  boot:
    admin:
      client:
        metadata:
          user.name: ${security.user.name}
          user.password: ${security.user.password}
        prefer-ip: true
        management-base-url: ${management.context-path}
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  session:
    store-type: none
info:
  app:
    name: zuul
    description: 网关服务
  build:
    groupId: spring.cloud.jmd
    artifact: zuul
    version: 0.0.1-SNAPSHOT
logging:
  level:
    root: info
  path: log/${spring.application.name}
foo: 123