security:
  basic:
    enabled: true
    path: ${management.context-path}
  user:
    name: jmd
    password: jmd123456
  oauth2:
    client:
      clientId: webApp2
      clientSecret: webApp2
      accessTokenUri: http://192.168.21.24:9093/auth/oauth/token
      userAuthorizationUri: http://192.168.21.24:9093/auth/oauth/authorize
    resource:
      id: jmd-monitor
      user-info-uri: http://192.168.21.24:9093/auth/user
      prefer-token-info: false
      filter-order: 3
spring:
  boot:
    admin:
      username: ${security.user.name}
      password: ${security.user.password}
      client:
        metadata:
          user.name: ${security.user.name}
          user.password: ${security.user.password}
        prefer-ip: true
        management-base-url: ${management.context-path}
        service-base-url: ${management.context-path}
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
      turbine:
        clusters: main,auth
        location: ${spring.application.name}
      context-path: /monitor
info:
  app:
    name: monitor
    description: 监控服务
  build:
    groupId: spring.cloud.jmd
    artifact: monitor
    version: 0.0.1-SNAPSHOT
logging:
  level:
    root: info
  path: log/${spring.application.name}
turbine:
  instanceUrlSuffix:
    auth: auth/mgmt/hystrix.stream
    main:  mgmt/hystrix.stream
  aggregator:
    clusterConfig: main,auth
  cluster-name-expression: metadata['cluster']
  appConfig: JMD-CONFIG,JMD-AUTH,JMD-ZUUl